### ISSUE TITLE
Consider way to support multiple devices of same model

### ISSUE THREAD

**Issue by KaoruNishikawa** [necst-telescope/neclib#178]
**Motivation**

- With no feature like this, flexibility is not enough to say the system is applicable to any telescope

**Possible solution**

- Accept single config blob with all parameter as an init argument.

  ```python
  def __init__(self, conf: SingleNamespace) -> None:
  ```

  - Instance would be created in necst. Parameters are passed from executor script. Could this be called a method that *don't require knowledge on device* model?
  - Or make executor script accept command-line argument, which can be passed from launch file?

- Make device classes accept config as init argument, then assign it by `partial` in `devices/selector.py` or `devices/__init__.py`.
  - It's not trivial how to get config blob

  ```python
  setattr(here, k, partial(impl, config))
  ```

- ~Define device ID (like `weather_station_container`) in config file, and use the ID to provide configuration parameters~

  ```toml
  dev_weather_station_container = "TR73U"
  dev_weather_station_cabin = "TR72W"

  weather_station_container_port = "/dev/ttyUSB0"
  weather_station_cabin_port = "/dev/ttyUSB1"
  ```

  - Decline this, as this implementation requires the necst to know device ID, i.e. `weather_station_container` should be used, instead of `weather_station`

- Define device ID in inline table, and use it to provide configuration parameters

  ```toml
  dev_weather_station = { container = "TR73U", cabin = "TR72W" }
  weather_station_port = { container = "/dev/ttyUSB0", cabin = "/dev/ttyUSB1" }
  ```

  - All devices belong to `weather_station` would be wrapped as if they are single device, and would be controlled by necst
  - Would cause a trouble when the devices are controlled by different computers (?)

- Singleton-like design, the class manages all its instances
  - `__new__` method eagerly searches relative parameters in config files
    - Return `None` if not configured
    - Return single instance if single configuration found
    - Return multiple instances if multiple configurations found (is this possible?)
  - How to get specific instance?

- Use object name (`dev_xxxxx`) as parameter prefix

- Make semi-singleton object
  - class knows its instances
  - `__new__` judge whether new config points to identical device to known instance or not
    - If identical, return the known instance
    - If not, create new one

- Add restriction on parameter naming
  - Parameters for `dev_antenna_motor` should be prefixed with `antenna_motor_<model>_<id>`
  - The parameters are passed to the instance, via `partial` in selector
  ```python
  setattr(here, k, partial(impl, config))
  ```
