### ISSUE TITLE
Modify Alab_config.toml

### ISSUE THREAD

**Issue by TatsumiISHIKAWA** [necst-telescope/neclib#665]
https://github.com/necst-telescope/neclib/blob/2ffe992f01d5bec74a819842b9fd510785924b2f/neclib/defaults/Alab_config.toml#L25-L29

https://github.com/necst-telescope/neclib/blob/2ffe992f01d5bec74a819842b9fd510785924b2f/neclib/defaults/Alab_config.toml#L70-L75

```toml
[signal_generator.agilent]

...

[local_attenuator]
_ = "CPZ340516"
channel = { sis_ch1 = 2 }
range = "DA0_100mA"
rate = 0.1
rsw_id = 0
```

https://github.com/necst-telescope/neclib/blob/eba598cf8da38ae4f5dd0e9a5e5cc9bfde4c9152/neclib/devices/motor/azd_ad.py#L65

- there is not `velosity`, it is `speed` in ogameasure
